enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"

[YouTube]
enabled = true
app-name = "YouTube"
build-mode = "both"#both means packing both apk and module at the same time. To pack only mask module, change both to module
version = "19.16.39"#Remember to check the patch support version before each package
rv-brand = "ReVanced Extended"
#Remember to change these two versions when the patch is updated
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Custom branding name for YouTube'"#Exclusion list
included-patches = "'Custom header for YouTube'"#Mandatory inclusion list Patches have a default list, some are disabled by default
patcher-args = "-e 'Return YouTube Username' -e 'Custom branding icon for YouTube' -OappIcon='mmt_green' -OchangeSplashIcon='true' -OrestoreOldSplashAnimation='true'   -e 'Visual preferences icons for YouTube'  -OsettingsMenuIcon='yt_alt' -OapplyToAll='true' -e 'Custom Shorts action buttons' -OiconType='Cairo' -e 'Custom header for YouTube' -OcustomHeader='custom_branding_icon' -e 'Theme' -OdarkThemeBackgroundColor=#FF111111 -e 'Settings for YouTube' -OsettingsLabel='Revanced Extended'"

[Instagram]
enabled = true
build-mode = "both"
patches-source = "Aunali321/ReVancedExperiments"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
version = "359.0.0.59.89"
arch = "arm64-v8a"  

[Telegram]
enabled = true
build-mode = "both"
patches-source = "Aunali321/ReVancedExperiments"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram/"
version = "auto"

[Music-Extended]
enabled = true
app-name = "YT Music"
patcher-args = "-e 'Custom branding name for YouTube Music' -OappNameNotification='YT Music' -OappNameLauncher='YT Music' -e 'Custom branding icon for YouTube Music' -OappIcon='vanced_black' -OchangeSplashIcon='true' -OrestoreOldSplashAnimation='true' -e 'Custom header for YouTube Music' -OcustomHeader='custom_branding_icon' -e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon='custom_branding_icon' -e 'Settings for YouTube Music' -OsettingsLabel='YT Premium'"
version = "auto"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[ReVanced]
enabled = true
build-mode = "both"
patches-source = "ReVanced/revanced-patches"
excluded-patches = ""
included-patches = "'Enable slide to seek' 'Custom branding' 'Change header' 'Remove player controls background'"
patcher-args = "-OappName=YouTube -OiconPath=mmt "
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Spotify]
enabled = true
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
patcher-args = "-d 'Spoof package info' -e 'Custom theme' -ObackgroundColor=@android:color/black -OoverridePlayerGradientColor=true -ObackgroundColorSecondary=#FF121212 -OaccentColor=#FF1ED760 -OaccentColorPressed=#FF169C46"
